/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aeg.giocomap.View;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.awt.Dimension;
/**
 *
 * @author Utente
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    // Bottone chat sempre visibile: viene messo sul JLayeredPane gia' integrato
    // nel JFrame (getLayeredPane), su un livello sopra al content pane. Cosi
    // fluttua sopra qualunque scena senza interferire con mostraPannello()
    private javax.swing.JButton btnChatFluttuante;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        // Impedire di rimpicciolire o modificare la grandezza della finestra
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        java.awt.Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize(); // Adatto alle dimensioni max dello schermo
        setMinimumSize(new Dimension(1024, 768));


        java.net.URL iconURL = getClass().getResource("/sprites/Oggetti/Tessuto.png");
        if(iconURL != null){
            javax.swing.ImageIcon icona = new javax.swing.ImageIcon(iconURL);
            this.setIconImage(icona.getImage());
            System.out.println("DEBUG: Immagine caricata");
        }
        else System.out.println("DEBUG: Errore di caricamento foto");

        impostaBottoneChat();
    }

    private void impostaBottoneChat() {
        // stesso stile dei bottoni del TitleScreen: bianco, testo nero, Arial bold
        btnChatFluttuante = new javax.swing.JButton("Chat");
        btnChatFluttuante.setFocusable(false);
        btnChatFluttuante.setBackground(java.awt.Color.WHITE);
        btnChatFluttuante.setForeground(java.awt.Color.BLACK);
        btnChatFluttuante.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        btnChatFluttuante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // POPUP_LAYER sta sopra al content pane (dove vanno le scene)
        getLayeredPane().add(btnChatFluttuante, javax.swing.JLayeredPane.POPUP_LAYER);

        // riposiziona il bottone quando la finestra cambia dimensione
        getRootPane().addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                riposizionaBottoneChat();
            }
        });
        riposizionaBottoneChat();
    }

    private void riposizionaBottoneChat() {
        if (btnChatFluttuante == null) return;
        // angolo in alto a destra, cosi non copre la box di dialogo in basso
        int btnW = 110;
        int btnH = 38;
        int margine = 20;
        int w = getLayeredPane().getWidth();
        btnChatFluttuante.setBounds(w - btnW - margine, margine, btnW, btnH);
    }

    // registra l'azione da eseguire al click del bottone chat fluttuante
    public void setChatListener(java.awt.event.ActionListener listener) {
        btnChatFluttuante.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adventure Game MAP");
        setIconImage(getIconImage());
        setIconImages(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1063, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    // Funzione per cambiare scenari
    public void mostraPannello(javax.swing.JPanel newPanel){
        // Rimuovo gli elementi della scena attuale
        this.getContentPane().removeAll();

        // Creo una nuova paginazione con nuove regole per la nuova scena
        this.getContentPane().setLayout(new java.awt.BorderLayout());

        // Inserisco la nuova scena
        this.getContentPane().add(newPanel, java.awt.BorderLayout.CENTER);

        // Ricalibrare la finestra grafica
        this.revalidate();
        this.repaint();

        // il bottone chat vive sul layeredPane del frame, lo tengo sempre
        // in primo piano sopra la nuova scena
        if (btnChatFluttuante != null) {
            getLayeredPane().setLayer(btnChatFluttuante, javax.swing.JLayeredPane.POPUP_LAYER);
            riposizionaBottoneChat();
            btnChatFluttuante.repaint();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
